/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SegurancaRouteImport } from './routes/seguranca'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PagamentosRouteImport } from './routes/pagamentos'
import { Route as FerramentasRouteImport } from './routes/ferramentas'
import { Route as CriptografiaRouteImport } from './routes/criptografia'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SegurancaSlugRouteImport } from './routes/seguranca.$slug'
import { Route as PrivacidadeSlugRouteImport } from './routes/privacidade.$slug'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SegurancaRoute = SegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentosRoute = PagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const FerramentasRoute = FerramentasRouteImport.update({
  id: '/ferramentas',
  path: '/ferramentas',
  getParentRoute: () => rootRouteImport,
} as any)
const CriptografiaRoute = CriptografiaRouteImport.update({
  id: '/criptografia',
  path: '/criptografia',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SegurancaSlugRoute = SegurancaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SegurancaRoute,
} as any)
const PrivacidadeSlugRoute = PrivacidadeSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PrivacidadeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/criptografia': typeof CriptografiaRoute
  '/ferramentas': typeof FerramentasRoute
  '/pagamentos': typeof PagamentosRoute
  '/privacidade': typeof PrivacidadeRouteWithChildren
  '/seguranca': typeof SegurancaRouteWithChildren
  '/sobre': typeof SobreRoute
  '/privacidade/$slug': typeof PrivacidadeSlugRoute
  '/seguranca/$slug': typeof SegurancaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/criptografia': typeof CriptografiaRoute
  '/ferramentas': typeof FerramentasRoute
  '/pagamentos': typeof PagamentosRoute
  '/privacidade': typeof PrivacidadeRouteWithChildren
  '/seguranca': typeof SegurancaRouteWithChildren
  '/sobre': typeof SobreRoute
  '/privacidade/$slug': typeof PrivacidadeSlugRoute
  '/seguranca/$slug': typeof SegurancaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/criptografia': typeof CriptografiaRoute
  '/ferramentas': typeof FerramentasRoute
  '/pagamentos': typeof PagamentosRoute
  '/privacidade': typeof PrivacidadeRouteWithChildren
  '/seguranca': typeof SegurancaRouteWithChildren
  '/sobre': typeof SobreRoute
  '/privacidade/$slug': typeof PrivacidadeSlugRoute
  '/seguranca/$slug': typeof SegurancaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/criptografia'
    | '/ferramentas'
    | '/pagamentos'
    | '/privacidade'
    | '/seguranca'
    | '/sobre'
    | '/privacidade/$slug'
    | '/seguranca/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/criptografia'
    | '/ferramentas'
    | '/pagamentos'
    | '/privacidade'
    | '/seguranca'
    | '/sobre'
    | '/privacidade/$slug'
    | '/seguranca/$slug'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/criptografia'
    | '/ferramentas'
    | '/pagamentos'
    | '/privacidade'
    | '/seguranca'
    | '/sobre'
    | '/privacidade/$slug'
    | '/seguranca/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  CriptografiaRoute: typeof CriptografiaRoute
  FerramentasRoute: typeof FerramentasRoute
  PagamentosRoute: typeof PagamentosRoute
  PrivacidadeRoute: typeof PrivacidadeRouteWithChildren
  SegurancaRoute: typeof SegurancaRouteWithChildren
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguranca': {
      id: '/seguranca'
      path: '/seguranca'
      fullPath: '/seguranca'
      preLoaderRoute: typeof SegurancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamentos': {
      id: '/pagamentos'
      path: '/pagamentos'
      fullPath: '/pagamentos'
      preLoaderRoute: typeof PagamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas': {
      id: '/ferramentas'
      path: '/ferramentas'
      fullPath: '/ferramentas'
      preLoaderRoute: typeof FerramentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criptografia': {
      id: '/criptografia'
      path: '/criptografia'
      fullPath: '/criptografia'
      preLoaderRoute: typeof CriptografiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguranca/$slug': {
      id: '/seguranca/$slug'
      path: '/$slug'
      fullPath: '/seguranca/$slug'
      preLoaderRoute: typeof SegurancaSlugRouteImport
      parentRoute: typeof SegurancaRoute
    }
    '/privacidade/$slug': {
      id: '/privacidade/$slug'
      path: '/$slug'
      fullPath: '/privacidade/$slug'
      preLoaderRoute: typeof PrivacidadeSlugRouteImport
      parentRoute: typeof PrivacidadeRoute
    }
  }
}

interface PrivacidadeRouteChildren {
  PrivacidadeSlugRoute: typeof PrivacidadeSlugRoute
}

const PrivacidadeRouteChildren: PrivacidadeRouteChildren = {
  PrivacidadeSlugRoute: PrivacidadeSlugRoute,
}

const PrivacidadeRouteWithChildren = PrivacidadeRoute._addFileChildren(
  PrivacidadeRouteChildren,
)

interface SegurancaRouteChildren {
  SegurancaSlugRoute: typeof SegurancaSlugRoute
}

const SegurancaRouteChildren: SegurancaRouteChildren = {
  SegurancaSlugRoute: SegurancaSlugRoute,
}

const SegurancaRouteWithChildren = SegurancaRoute._addFileChildren(
  SegurancaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  CriptografiaRoute: CriptografiaRoute,
  FerramentasRoute: FerramentasRoute,
  PagamentosRoute: PagamentosRoute,
  PrivacidadeRoute: PrivacidadeRouteWithChildren,
  SegurancaRoute: SegurancaRouteWithChildren,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
