/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SegurancaSlugRouteImport } from './routes/seguranca.$slug'
import { Route as PrivacidadeSlugRouteImport } from './routes/privacidade.$slug'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SegurancaSlugRoute = SegurancaSlugRouteImport.update({
  id: '/seguranca/$slug',
  path: '/seguranca/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeSlugRoute = PrivacidadeSlugRouteImport.update({
  id: '/privacidade/$slug',
  path: '/privacidade/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/sobre': typeof SobreRoute
  '/privacidade/$slug': typeof PrivacidadeSlugRoute
  '/seguranca/$slug': typeof SegurancaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/sobre': typeof SobreRoute
  '/privacidade/$slug': typeof PrivacidadeSlugRoute
  '/seguranca/$slug': typeof SegurancaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/sobre': typeof SobreRoute
  '/privacidade/$slug': typeof PrivacidadeSlugRoute
  '/seguranca/$slug': typeof SegurancaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/sobre'
    | '/privacidade/$slug'
    | '/seguranca/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contato' | '/sobre' | '/privacidade/$slug' | '/seguranca/$slug'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/sobre'
    | '/privacidade/$slug'
    | '/seguranca/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  SobreRoute: typeof SobreRoute
  PrivacidadeSlugRoute: typeof PrivacidadeSlugRoute
  SegurancaSlugRoute: typeof SegurancaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguranca/$slug': {
      id: '/seguranca/$slug'
      path: '/seguranca/$slug'
      fullPath: '/seguranca/$slug'
      preLoaderRoute: typeof SegurancaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade/$slug': {
      id: '/privacidade/$slug'
      path: '/privacidade/$slug'
      fullPath: '/privacidade/$slug'
      preLoaderRoute: typeof PrivacidadeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  SobreRoute: SobreRoute,
  PrivacidadeSlugRoute: PrivacidadeSlugRoute,
  SegurancaSlugRoute: SegurancaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
